apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: radhakrishnangopal/node-api:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-api
spec:
  type: NodePort
  selector:
    app: node-api
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30967
